name: 'build test deploy'

on:
  push:
    branches: [ CAY-2708-GRADLE-PLUGIN-BUILD-FAILS ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - name: Set up JDK...
        uses: actions/setup-java@v1
        with:
          java-version: '16'

      - name: Retrieve mvn repo cache...
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-build-v1
          restore-keys: ${{ runner.os }}-maven
      
      - name: Build snapshots
        run: | 
          mvn clean install -DskipTests

      - name: Build and test...
        run: | 
          mvn clean install -DskipTests
          ./gradlew build
        working-directory: cayenne-gradle-plugin
